name: Magento Developer Documentation
markdown: kramdown
highlighter: pygments
encoding: utf-8
baseurl: /pages/Magento/devdocs_internal/
gdeurl: /pages/Magento/devdocs_internal/guides/v1.0/
description: Magento 2 Developer's Guide
githuburl: https://github.scm.corp.ebay.com/Magento/devdocs_internal/tree/devbeta/guides/v1.0/
namem2fedg: Magento 2 Frontend Developer Guide
namem2devgde: Magento 2 Developer Guide
namem2apiref: Magento 2 API Reference
namem2install: Magento 2 Installation and Upgrade Guide
mage2000url: https://github.com/magento/magento2/blob/master/










