name: Magento Developer Documentation
markdown: kramdown
highlighter: pygments
baseurl: /pages/Magento/devdocs_internal/
description: Magento 2 Developer's Guide
githuburl: https://github.scm.corp.ebay.com/Magento/devdocs_internal/tree/master/
namem2fedg: Magento 2 Frontend Developer's Guide
namem2devgde: Magento 2 Developer's Guide
