html_proofer:
  file_ignore:
    - 404.html
    - action-groups.html
    - cloud-fastly.html
    - codelinks
    - contributing.html
    - css-preprocess.html
    - es-overview.html
    - guides/m1x
    - index.html
    - magento-third-party.html
    - magento-techbull.html
    - mftf
    - pattern-library
    - release-notes
    - search.html
    - swagger
    - template.html
    - theme_dictionary.html
    - videos
    - whats-new.html

  url_ignore:
    - account.magento.com
    - config-guide
    - docs.magento.com
    - extension-dev-guide
    - frontend-dev-guide
    - github.com
    - guides/v2.0
    - howdoi
    - mariadb.com
    - mftf
    - mrg
    - navigation
    - pattern-library
    - release-notes
    - rest
    - ui_comp_guide
    - www.thegeekstuff.com
    - yatil.net
