# Site settings 
encoding: "utf-8"
title: Magento 2 Developer Documentation
email: mailto:DL-Magento-Doc-Feedback@ebay.com
description: > # this means to ignore newlines until "baseurl:"
  Magento 2 Developer Guide.
baseurl: "/"
description: Magento 2 Developer's Guide
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gdeurl: "/pages/magento/devdocs/guides/v1.0/"
githuburl: "http://github.com/magento/devdocs/blob/master/"
namem2fedg: "Magento 2 Frontend Developer's Guide"
namem2devgde: "Magento 2 Developer's Guide"
namem2apiref: "Magento 2 API Reference"
namem2install: "Magento 2 Installation Guide"
mage2000url: "https://github.com/magento/magento2/blob/master/"
toc_baseurl: "https://github.com/pages/magento/devdocs"

# Build settings
markdown: kramdown
highlighter: pygments
