name: Magento 2 Developer's Guide
markdown: kramdown
highlighter: pygments
baseurl: /pages/Magento/devdocs_internal/
description: Magento 2 Developer's Guide
githuburl: https://github.scm.corp.ebay.com/Magento/devdocs_internal/tree/master/