name: Magento Developer Documentation
markdown: kramdown
highlighter: pygments
encoding: utf-8
baseurl: /pages/stevjohnson/devdocs_internal/
description: Magento 2 Developer's Guide
githuburl: https://github.scm.corp.ebay.com/stevjohnson/devdocs_internal/tree/master/
namem2fedg: Magento 2 Frontend Developer's Guide
namem2devgde: Magento 2 Developer's Guide

