name: Magento Developer Documentation
markdown: kramdown
highlighter: pygments
baseurl: /pages/difleming/devdocs_internal/
description: Magento Developer Documentation
githuburl: https://github.scm.corp.ebay.com/difleming/devdocs_internal/tree/master/
namem2fedg: Magento 2 Front-end Developer Guide
namem2devgde: Magento 2 Developer Guide
namem2apiref: Magento 2 API Reference
