html_proofer:
  file_ignore:
    - videos
    - swagger
    - mftf
    - pattern-library
    - guides/m1x
    - search.html
    - 404.html
    - codelinks
    - magento-third-party.html
    - magento-techbull.html
    - release-notes
    - index.html
    - template.html
    - whats-new.html
    - action-groups.html
    - css-preprocess.html
    - es-overview.html
    - cloud-fastly.html
    - theme_dictionary.html
    - contributing.html

  url_ignore:
    - guides/v2.0
    - architecture
    - advanced-reporting
    - coding-standards
    - comp-mgr
    - config-guide
    - contributor-guide
    - design-styleguide
    - ext-best-practices
    - extension-dev-guide
    - frontend-dev-guide
    - get-started
    - graphql
    - howdoi
    - inventory
    - javascript-dev-guide
    - marketplace
    - magento-functional-testing-framework
    - migration
    - modules
    - mrg
    - mtf
    - pattern-library
    - payments-integrations
    - release-notes
    - rest
    - soap
    - test
    - ui-components
    - ui_comp_guide
    - pwa
    - msi
    - mftf
    - github.com
    - www.thegeekstuff.com
    - account.magento.com
    - yatil.net
    - ui-library
    - security
    - navigation
    - community
    - docs.magento.com
    - mariadb.com
