name: Markdown linting test

on:
  pull_request:
    branches:
      - master
      - develop
      - ds_add-mdl-check
    paths:
      - '*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
#     - name: Update RubyGems
#       run: gem update --system
    - name: Install gems
      run: bundle install
    - name: Run mdl
      run: rake test:md
