---
title: Magento_CatalogRuleConfigurable
edition: ce
content: 'Magento_CatalogRuleConfigurable module is an extension of Magento_CatalogRule
  and Magento_ConfigurableProduct modules that handle catalog rule indexer for configurable
  product

  '
last_modified_at: '2015-09-07 17:18:34 +0300'
