---
title: Magento_ConfigurableProductSales
edition: ce
content: "# Magento_ConfigurableProductSales module\n\nThe Magento_ConfigurableProductSales
  module checks that the selected options of order item are still presented in\nCatalog.
  Returns true if the previously ordered item configuration is still available. "
