---
title: Magento_MsrpConfigurableProduct
edition: ce
content: "**MsrpConfigurableProduct** provides type and resolver information for the
  Msrp module from the ConfigurableProduct module."
last_modified_at: '2019-03-02 19:21:49 -0600'
