---
title: Magento_ProductVideo
edition: ce
content: 'The Magento_ProductVideo module implements functionality related with linking
  video files from external resources to product.

  '
last_modified_at: '2015-09-11 16:19:20 +0300'
